extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_stone_lights;
extern Lights1 castle_grounds_dl_bobtop_lights;
extern Lights1 castle_grounds_dl_bobdown_lights;
extern u8 castle_grounds_dl_sm64grass_ci8[];
extern u8 castle_grounds_dl_sm64grass_pal_rgba16[];
extern u8 castle_grounds_dl_sm64stone_i8[];
extern u8 castle_grounds_dl_BOB_Paintingtop_rgba16[];
extern u8 castle_grounds_dl_BOB_Paintingdown_rgba16[];
extern Vtx castle_grounds_dl_outside_mesh_layer_1_vtx_0[128];
extern Vtx castle_grounds_dl_outside_mesh_layer_1_vtx_1[175];
extern Vtx castle_grounds_dl_outside_mesh_layer_1_vtx_2[26];
extern Vtx castle_grounds_dl_outside_001_mesh_layer_4_vtx_0[4];
extern Vtx castle_grounds_dl_outside_001_mesh_layer_4_vtx_1[4];
extern Gfx castle_grounds_dl_outside_mesh_layer_1[];
extern Gfx castle_grounds_dl_outside_001_mesh_layer_4[];
